Add created and updated fields to folders
NDLANO/backend pull request #161
Opened 2022-12-28 14:32 UTC by N4G1

Fixes: https://github.com/NDLANO/Issues/issues/3311

TODO: Add updated field to Folders

2022-12-28 14:52 UTC, N4G1 commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
> +                SELECT id, parent_id, feide_id, name, status, rank, created
Den sql'en her er litt tricky. Siden vi spesifiserer feltene individuelt ved uthenting, må vi huske å oppdatere denne sql'en for hver ny felt vi legger i Folder klassen. Har laget en regresjonstest på denne funksjonen nå, men vi har en bug fordi at `rank` var ikke spesifisert. `rank` feltet ble introdusert i august så buggen har levd lenge men tydeligvis henter vi ikke folders med kun subfolders alt for ofte for ellers hadde vi fått vite om at noe ikke fungerer. Kan framprovoseres på f.eks: `https://test.api.ndla.no/learningpath-api/v1/folders/?include-subfolders=true`

Går det an å futureproofe sql'en ved å f.eks bruke `*` ?

2023-01-26 13:40 UTC, gunnarvelle requested changes

2023-01-26 13:40 UTC, gunnarvelle commented on learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V28__AddLastSharedFieldToFolders.sql
> +ADD COLUMN last_shared TIMESTAMP DEFAULT NULL;
Slå sammen disse to migreringene. Dette er en endring og ikkje to, spesielt siden du endrer på samme tabell.
Du har ikkje brukt last_updated så då treng du heller ikkje last_shared.
```suggestion
ADD COLUMN shared TIMESTAMP DEFAULT NULL;
```

2023-01-26 13:40 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Folder.scala
> +    @(ApiModelProperty @field)(description = "When the folder was last shared") lastShared: Option[LocalDateTime]
```suggestion
    @(ApiModelProperty @field)(description = "When the folder was last shared") shared: Option[LocalDateTime]
```

2023-01-26 13:40 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    lastShared: Option[LocalDateTime]
Kvifor treng du denne her?

2023-01-31 08:54 UTC, N4G1 commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    lastShared: Option[LocalDateTime]
Fordi den skal lagres i databasen, eller hva mener du? Den brukes f.eks i `toNewFolderData(..)` funksjonen i `ConverterService`.

2023-01-31 09:26 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    lastShared: Option[LocalDateTime]
Eg berre stussa på at den ligger i NewFolderData. Du vil sannsynligvis ikkje opprette ei ny tom delt mappe.

2023-01-31 09:31 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    shared: Option[LocalDateTime]
Må denne være med som parameter? Den settes jo ved endring av status, som allerede er med som parameter?
Metoden ser ut som kalles fra insertFolder og ser ikkje at denne trenger å være med.

2023-01-31 14:11 UTC, N4G1 commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    lastShared: Option[LocalDateTime]
Det skal kanskje ikke være sannsynlig fra frontend-perspektive men fra api går det fint an. Og hva skjer om man faktisk gjør det? Da får vi status `shared` på mappa uten tidsstempel.  Skal vi heller fjerne muligheten å sette status i api typen i `api.NewFolder` ?

2023-01-31 14:30 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    lastShared: Option[LocalDateTime]
Nei, kan godt ha status i NewFolderData, men då må vi berre sette shared ved oppretting.

2023-01-31 14:33 UTC, N4G1 commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    lastShared: Option[LocalDateTime]
Ja, slik det er nå. Så da lar jeg det stå.

2023-01-31 14:45 UTC, gunnarvelle requested changes
Sånn det er no så legger du ansvaret for oppdatering av shared feil plass. Ingen av dei andre datoene håndteres slik og det burde ikkje shared gjøres heller.
Har lagt inn forslag til korleis eg tenker dette burde fungerer.

2023-01-31 14:45 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +    shared: Option[LocalDateTime]
```suggestion
    rank: Option[Int]
```

2023-01-31 14:45 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
> +      updated: LocalDateTime
```suggestion
      created: LocalDateTime,
      updated: LocalDateTime,
      shared: Option[LocalDateTime]
```

2023-01-31 14:45 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
> +        val updated = created
```suggestion
        val created = clock.now()
        val updated = created
        val shared = if(folderData.status == FolderStatus.SHARED) Some(clock.now()) else None
```

2023-01-31 14:45 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
> +        values ($newId, ${folderData.parentId}, $feideId, ${folderData.name}, ${folderData.status.toString}, ${folderData.rank}, $created, $updated, ${folderData.shared})
```suggestion
        insert into ${DBFolder.table} (id, parent_id, feide_id, name, status, rank, created, updated, shared)
        values ($newId, ${folderData.parentId}, $feideId, ${folderData.name}, ${folderData.status.toString}, ${folderData.rank}, $created, $updated, $shared)
```

2023-01-31 14:45 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
> +          updated = updated
```suggestion
          created = created,
          updated = updated,
          shared = shared
```

2023-02-01 08:51 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
> +              shared=${folder.shared}
Trengs egentlig denne no?

2023-02-01 08:51 UTC, gunnarvelle commented on learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
> +      val shared = if (status == FolderStatus.SHARED) Some(clock.now()) else None
Kalles denne metoden ved alle lagringer? Då burde vi sjekke at existing.status != updated.status også.

2023-02-01 14:16 UTC, jnatten commented on learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V27__AddCreatedAndUpdatedFieldsToFolders.sql
> +ADD COLUMN updated TIMESTAMP DEFAULT NOW(),
Burde disse være `NOT NULL`

2023-02-01 14:34 UTC, gunnarvelle approved these changes
LGTM

2023-02-01 14:41 UTC, merged