Add responsible field to concept
NDLANO/backend pull request #173
Opened 2023-01-31 14:55 UTC by MaPoKen

relates to https://github.com/NDLANO/Issues/issues/3428

Legge til responsefield til concepts. Tilnærme kopi av https://github.com/NDLANO/backend/pull/109

2023-01-31 15:31 UTC, gunnarvelle reviewed
Kan godt lage noen tester også.

2023-01-31 15:31 UTC, gunnarvelle commented on concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptResponsible.scala
> + * Copyright (C) 2017 NDLA
```suggestion
 * Copyright (C) 2023 NDLA
```

2023-01-31 15:31 UTC, gunnarvelle commented on concept-api/src/main/scala/no/ndla/conceptapi/model/api/NewConcept.scala
> +    @(ApiModelProperty @field)(description = "DLA ID representing the editor responsible for this article") responsibleId: Option[String]
```suggestion
    @(ApiModelProperty @field)(description = "NDLA ID representing the editor responsible for this article") responsibleId: Option[String]
```

2023-01-31 15:31 UTC, gunnarvelle commented on concept-api/src/main/scala/no/ndla/conceptapi/model/domain/ConceptResponsible.scala
> +package no.ndla.conceptapi.model.domain
Lisens

2023-02-01 05:23 UTC, jnatten commented on concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
> +          domain.ConceptResponsible(responsibleId = responsibleId, lastUpdated = clock.now())
```suggestion
        responsible = concept.responsibleId.map(responsibleId =>
          domain.ConceptResponsible(responsibleId = responsibleId, lastUpdated = clock.now())
```

2023-02-01 08:51 UTC, gunnarvelle commented on concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
> +          domain.ConceptResponsible(responsibleId = responsibleId, lastUpdated = clock.now())
Ganske sentral fiks gitt.

2023-02-01 14:40 UTC, N4G1 commented
> Added test for responsible and modified existing test. Fixed pr comments

Litt småpirk men veldig nyttig for fremtiden. Commit messages burde beskrive endringene man har gjort. Den første setningen beskriver godt endringene, men siste setningen er veldig ambigiøst og sier egentlig ingenting. Dersom det er en verdifult endring som ble laget burde den da splittes i en separat commit og beskrives. Er ikke det case'n trenger du ikke å nevne det. 

Er veldig nyttig når man skal grave seg tilbake i committene og prøve å finne en spesifik endring. Å lese `Fixed pr commits` hjelper ingen å finne fram det de letter etter :sweat_smile:

2023-02-02 07:57 UTC, N4G1 requested changes
Små pirk

2023-02-02 07:57 UTC, N4G1 commented on concept-api/src/main/scala/no/ndla/conceptapi/model/api/Concept.scala
> +    @(ApiModelProperty @field)(description = "Object with data containing representing the editor responsible for this concept") responsible: Option[ConceptResponsible]
`containing representing` which is it? :sweat_smile:

2023-02-02 07:57 UTC, N4G1 commented on concept-api/src/main/scala/no/ndla/conceptapi/model/domain/ConceptResponsible.scala
> +case class ConceptResponsible(responsibleId: String, lastUpdated: LocalDateTime)
Jeg stemmer for at du gjør følgende:
- Flytt `DraftResponsible` fra `common.model.domain.draft` til `common.model.domain`
- Rename `DraftResponsible` til bare `Responsible`
- Slett denne og ta i bruk `Responsible` fra common

2023-02-02 07:57 UTC, N4G1 commented on concept-api/typescript/index.ts
> +  responsible?: IConceptResponsible
Du trenger ikke å kjøre manuelt `sbt concept-api/generateTypescript`. Dette skjer av seg selv etter at du merger PR'en din i master.

2023-02-02 14:11 UTC, gunnarvelle reviewed
Du må også utvide søket etter draft-concepts med responsibleId, for det trengs for at vi skal kunne lage arbeidsliste i ed.

2023-02-08 09:10 UTC, N4G1 approved these changes
LGTM

2023-02-13 07:27 UTC, merged